version: "3.5"
services:
  mrss-redis:
    container_name: mrss-redis-container
    restart: on-failure:5
    image: redis:alpine
  mrss-mongo:
    container_name: mrss-mongodb-container
    restart: on-failure:5
    command: mongod --port 27017
    image: mongo:latest
    volumes:
      - 'db-data:/data/db'
  mrss-bot:
    container_name: mrss-bot-container
    restart: on-failure:3
    build: .
    depends_on:
      - mrss-mongo
    environment:
      - DRSS_START=bot
      - DRSS_BOT_TOKEN=
      - DRSS_DATABASE_URI=mongodb://mrss-mongo:27017/rss
  mrss-web:
    container_name: mrss-web-container
    build: .
    restart: on-failure:3
    depends_on:
      - mrss-redis
      - mrss-mongo
    ports:
      - "8081:8081"
    environment:
      - DRSS_START=web
      - DRSSWEB_BOT_TOKEN=
      - DRSSWEB_DATABASE_REDIS=redis://mrss-redis:6379
      - DRSSWEB_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      - DRSSWEB_BOT_REDIRECTURI=
      - DRSSWEB_BOT_CLIENTID=
      - DRSSWEB_BOT_CLIENTSECRET=

volumes:
  db-data:
