version: "3.5"
services:
  mrss-redis:
    container_name: mrss-redis
    restart: unless-stopped
    image: redis:alpine
  mrss-mongo:
    container_name: mrss-mongodb
    restart: unless-stopped
    command: mongod --port 27017
    image: mongo:latest
    volumes:
      - ./path/to/config/db:/data/db
  mrss-bot:
    container_name: mrss-bot
    restart: unless-stopped
    image: griefed/monitorss-clone
    depends_on:
      - mrss-mongo
    environment:
      - TZ=Europe/Berlin
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - DRSS_START=bot
      - DRSS_BOT_TOKEN=
      - DRSS_DATABASE_URI=mongodb://mrss-mongo:27017/rss
    volumes:
      - ./path/to/config/bot:/config
  mrss-web:
    container_name: mrss-web
    image: griefed/monitorss-clone
    restart: unless-stopped
    depends_on:
      - mrss-redis
      - mrss-mongo
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Berlin
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - DRSS_START=web
      - DRSSWEB_BOT_TOKEN=
      - DRSSWEB_DATABASE_REDIS=redis://mrss-redis:6379
      - DRSSWEB_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      - DRSSWEB_BOT_REDIRECTURI=
      - DRSSWEB_BOT_CLIENTID=
      - DRSSWEB_BOT_CLIENTSECRET=
    volumes:
      - ./path/to/config/web:/config