#!/usr/bin/with-contenv bash

if [ ! -f /config/config.bot.json ]; then
  cp /defaults/config.bot.json \
     /config/config.bot.json
  echo "**** Setting DRSS_DATABASE_URI ****"
  sed -i \
  "s#DRSSBOTTOKEN#${DRSS_BOT_TOKEN}#g" \
  /config/config.bot.json
  sed -i \
  "s#DRSSDATABASEURI#${DRSS_DATABASE_URI}#g" \
  /config/config.bot.json
  echo "**** Setting TZ ****"
  sed -i \
  "s#TZ#${TZ}#g" \
  /config/config.bot.json
fi

if [ ! -f /config/config.web.json ]; then
  cp /defaults/config.web.json \
     /config/config.web.json
  echo "**** Setting DRSSWEB_BOT_REDIRECTURI ****"
  sed -i \
  "s#DRSSWEBBOTREDIRECTURI#${DRSSWEB_BOT_REDIRECTURI}#g" \
  /config/config.web.json
  echo "**** Setting DRSSWEB_DATABASE_URI ****"
  sed -i \
  "s#DRSSWEBDATABASEURI#${DRSSWEB_DATABASE_URI}#g" \
  /config/config.web.json
  echo "**** Setting DRSSWEB_DATABASE_REDIS ****"
  sed -i \
  "s#DRSSWEBDATABASEREDIS#${DRSSWEB_DATABASE_REDIS}#g" \
  /config/config.web.json
  echo "**** Setting DRSSWEB_SESSION_SECRET ****"
  sed -i \
  "s#DRSSWEBSESSIONSECRET#${DRSSWEB_SESSION_SECRET}#g" \
  /config/config.web.json
  echo "**** Setting DRSS_BOT_TOKEN ****"
  sed -i \
  "s#DRSSBOTTOKEN#${DRSS_BOT_TOKEN}#g" \
  /config/config.web.json
  echo "**** Setting DRSSWEB_BOT_CLIENTID ****"
  sed -i \
  "s#DRSSWEBBOTCLIENTID#${DRSSWEB_BOT_CLIENTID}#g" \
  /config/config.web.json
  echo "**** Setting DRSSWEB_BOT_CLIENTSECRET ****"
  sed -i \
  "s#DRSSWEBBOTCLIENTSECRET#${DRSSWEB_BOT_CLIENTSECRET}#g" \
  /config/config.web.json
fi

if [ ! -f /config/schedules.json ]; then
  cp /defaults/schedules.json \
  /config/schedules.json
fi

echo "**** Ensuring permissions for user ****"
chown -R \
  abc:abc \
    /app/monitorss \
    /config

ln -sf /config/config.bot.json /app/monitorss/settings/config.bot.json
ln -sf /config/config.web.json /app/monitorss/settings/config.web.json
ln -sf /config/schedules.json /app/monitorss/settings/schedules.json