#!/usr/bin/with-contenv bash

DEFAULT_REDIRECT_URI='http://localhost:8081/authorize'

if [ ! -f /config/config.bot.json ]; then
  cp /defaults/config.bot.json \
     /config/config.bot.json
  sed -i \
  "s/DRSS_DATABASE_URI/$DRSS_DATABASE_URI/g" \
  /config/config.bot.json
  sed -i \
  "s/TZ/$TZ/g" \
  /config/config.bot.json
fi

if [ ! -f /config/config.web.json ]; then
  cp /defaults/config.web.json \
     /config/config.web.json
  sed -i \
  "s/DRSSWEB_BOT_REDIRECTURI/$DRSSWEB_BOT_REDIRECTURI/g" \
  /config/config.web.json
  sed -i \
  "s/DRSSWEB_DATABASE_URI/$DRSSWEB_DATABASE_URI/g" \
  /config/config.web.json
  sed -i \
  "s/DRSSWEB_DATABASE_REDIS/$DRSSWEB_DATABASE_REDIS/g" \
  /config/config.web.json
  sed -i \
  "s/DRSSWEB_SESSION_SECRET/$DRSSWEB_SESSION_SECRET/g" \
  /config/config.web.json
  sed -i \
  "s/DRSS_BOT_TOKEN/$DRSS_BOT_TOKEN/g" \
  /config/config.web.json
  sed -i \
  "s/DRSSWEB_BOT_CLIENTID/$DRSSWEB_BOT_CLIENTID/g" \
  /config/config.web.json
  sed -i \
  "s/DRSSWEB_BOT_CLIENTSECRET/$DRSSWEB_BOT_CLIENTSECRET/g" \
  /config/config.web.json
fi

if [ ! -f /config/schedules.json ]; then
  cp /defaults/schedules.json \
  /config/schedules.json
fi

echo "**** Ensuring permissions for user ****"
chown -R \
  abc:abc \
    /app/monitorss \
    /config

ln -sf /config/config.bot.json /app/monitorss/settings/config.bot.json
ln -sf /config/config.web.json /app/monitorss/settings/config.web.json
ln -sf /config/schedules.json /app/monitorss/settings/schedules.json